#!/usr/bin/env python

from astropy.io import fits
import numpy as np
import sys
import glob

def make_constant_weight(science_fits,
                         weight_fits,
                         skystd_key='SKYSTD',
                         headerkey='PANFZP'):
    """
    from chatgpt and RAF

    Create a constant inverse-variance weight map for SWarp.

    weight = 1 / (SKYSTD^2 * PANSCALE^2)
    Pixels where science image == 0 are given weight = 0.

    Parameters
    ----------
    science_fits : str
        Input sky-subtracted science image
    weight_fits : str
        Output weight image filename
    skystd_key : str
        Header keyword with sky RMS (before scaling)
    panscale_key : str
        Header keyword with photometric scale factor
    """
    hdu = fits.open(science_fits)
    data = hdu[0].data
    header = hdu[0].header

    skystd   = float(header[skystd_key])
    panfzp = float(header[headerkey])

    # Constant inverse-variance weight
    wconst = 1.0 / (skystd**2 * panfzp**2)

    weight = np.full(data.shape, wconst, dtype=np.float32)

    # Mask bad pixels (science image exactly zero)
    bad_mask = (data == 0) | ~np.isfinite(data)
    weight[bad_mask] = 0

    # Write weight map
    fits.writeto(weight_fits, weight, header, overwrite=True)

    if args.verbose:
        print(f"Wrote {weight_fits}")



if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description ="This program constructs a constant weight map using the header parameters SKYSTD (generated by subtract_median.py) and PANSCALE (generated by INT_get_ccd_offsets.py).  The weight maps can be used by swarp to properly downweight images with high values of PANSCALE.")
    parser.add_argument('--filestring', dest = 'filestring', default = 'WFC', help = 'filestring to match. default is WFC, which will grab all WFC*PA.fits.')
    parser.add_argument('--headerkey', dest = 'headerkey', default = 'PSCALE', help = 'header keyword to use for scaling.  Default is PANFZP, but PSCALE.')
    parser.add_argument('--verbose', dest = 'verbose', default = False, action='store_true', help = 'This may print more information')        
    parser.add_argument('--testing', dest = 'testing', default = False, action='store_true', help = 'Will run on one directory only.')
    
    args = parser.parse_args()    

    # glob all WFC*PA.fits (or mWFC*PA.fits)
    flist = glob.glob(f'{args.filestring}*PA.fits')
    flist.sort()
    if args.verbose:
        print("flist = ",flist)
    # look for unique set of all image prefixes among all the *1PA.fits *2PA.fits, etc files
    #allfilerootlist = [t.split('_')[0] for t in flist]
    #filerootlist = list(set(allfilerootlist))

    for f in flist:
        make_constant_weight(science_fits=f, weight_fits=f.replace('.fits','.weight.fits'),headerkey=args.headerkey)

        
        if args.testing:
            sys.exit()

            #1NE49thSt!
